---
- name: Configure network
  hosts: Routers
  gather_facts: no

  tasks:
    - name: Load router-specific variables
      include_vars:
        file: "{{ inventory_hostname }}.yml"

    - name: Generate router configuration
      template:
        src: template.j2
        dest: D:\BCU_Output\Result\{{ inventory_hostname }}-config.txt

    - name: Apply generated configuration using ios_config
      ios_config:
        src: D:\BCU_Output\Result\{{ inventory_hostname }}-config.txt
      register: result

    - name: Save Config
      when: result.changed
      ios_command:
        commands:
          - "write memory"
